#### Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.array([12,9,80,56])
arr1

array([12,  9, 80, 56])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
np.ndim(arr1)

1

In [5]:
arr1[3]

56

slicing
[starts:stop+1]

In [6]:
arr1[1:4]

array([ 9, 80, 56])

In [7]:
arr1.shape

(4,)

### 2D Array

In [8]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
np.ndim(arr2)

2

In [11]:
arr2.shape

(2, 4)

#### 3D Array

In [12]:
arr3 = np.array([[[1,2,3],
                  [4,5,6]],
                  
                  [[5,8,9],
                   [8,0,2]]])

In [13]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 8, 9],
        [8, 0, 2]]])

In [14]:
arr3.shape

(2, 2, 3)

In [15]:
np.ndim(arr3)

3

In [16]:
type(arr3)

numpy.ndarray

#### Reshape Function

In [17]:
arr3.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 8, 9],
       [8, 0, 2]])

In [18]:
arr3.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 5, 8],
       [9, 8, 0, 2]])

###### Keep Datatypes consistant in arrays

In [19]:
arr4 = np.array(['sayali' , 23 , 12.4 , True , 'x' , 12])

In [20]:
arr4

array(['sayali', '23', '12.4', 'True', 'x', '12'], dtype='<U32')

In [21]:
for i in arr4:
    print(f'Element Value : {i} , Element type : {type(i)}')

Element Value : sayali , Element type : <class 'numpy.str_'>
Element Value : 23 , Element type : <class 'numpy.str_'>
Element Value : 12.4 , Element type : <class 'numpy.str_'>
Element Value : True , Element type : <class 'numpy.str_'>
Element Value : x , Element type : <class 'numpy.str_'>
Element Value : 12 , Element type : <class 'numpy.str_'>


#### List vs Array Multiplied by 3

In [22]:
a = [3,4,5,6]
a

[3, 4, 5, 6]

In [23]:
type(a)

list

In [24]:
a*3

[3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6]

In [25]:
a*4

[3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6]

In [26]:
b = []
for i in a:
    b.append(3*i)

In [27]:
b

[9, 12, 15, 18]

In [28]:
c = np.array([9,7,8,4])
c

array([9, 7, 8, 4])

In [29]:
type(c)

numpy.ndarray

In [30]:
d = 3*c

In [31]:
d

array([27, 21, 24, 12])

#### Taking product of element inside list vs array

In [32]:
e = [5,6,7,8]
type(e)

list

In [33]:
e

[5, 6, 7, 8]

In [34]:
p=1
for i in e:
    p = p*i
print(f'product of element inside list {e} is {p}')

product of element inside list [5, 6, 7, 8] is 1680


In [35]:
5*6*7*8

1680

In [36]:
g = ([5,6,7,8])
type(g)

list

In [37]:
np.prod(g)

1680

In [38]:
np.sum(g)

26

#### Numpy Agrigation operations

In [39]:
A = np.array([7,8,9,23])

In [40]:
s = sum(A)
s

47

In [41]:
7+8+9+23

47

In [42]:
np.mean(A)

11.75

In [43]:
47/4

11.75

In [44]:
np.max(A)

23

In [45]:
np.min(A)

7

In [46]:
np.std(A)

6.53356717268599

In [47]:
np.prod(A)

11592

In [48]:
7*8*9*23

11592

#### Generating Data through Numpy

range(start,stop,step)

In [49]:
range(2,25,2)

range(2, 25, 2)

In [50]:
list(range(2,25,2))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]

In [51]:
list(range(0.1,3.5,0.2))

TypeError: 'float' object cannot be interpreted as an integer

#### np.arange

In [ ]:
B = np.arange(0.2,10.2,0.6)

In [ ]:
B

array([0.2, 0.8, 1.4, 2. , 2.6, 3.2, 3.8, 4.4, 5. , 5.6, 6.2, 6.8, 7.4,
       8. , 8.6, 9.2, 9.8])

In [ ]:
alphas = np.arange(0.1,100,0.1)
alphas

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15

#### Numpy Linspace

In [ ]:
c = np.linspace(2,10,5)
c

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
D = np.linspace(-0.1,20,10)
D

array([-0.1       ,  2.13333333,  4.36666667,  6.6       ,  8.83333333,
       11.06666667, 13.3       , 15.53333333, 17.76666667, 20.        ])

#### Generating Random numbers in Numpy

##### Generating numbers between 0 to 1 randomly

In [ ]:
np.random.seed(21)
n = np.random.random(20)
n

array([0.04872488, 0.28910966, 0.72096635, 0.02161625, 0.20592277,
       0.05077326, 0.30227189, 0.66391029, 0.30811439, 0.58359128,
       0.06957095, 0.86740448, 0.13324052, 0.17812466, 0.49592955,
       0.86369964, 0.75894384, 0.97048513, 0.75930255, 0.38425003])

In [ ]:
np.random.seed(21)
h = np.random.random(51)
h

array([0.04872488, 0.28910966, 0.72096635, 0.02161625, 0.20592277,
       0.05077326, 0.30227189, 0.66391029, 0.30811439, 0.58359128,
       0.06957095, 0.86740448, 0.13324052, 0.17812466, 0.49592955,
       0.86369964, 0.75894384, 0.97048513, 0.75930255, 0.38425003,
       0.40871833, 0.71336043, 0.27066977, 0.85410287, 0.91316397,
       0.76075607, 0.51666854, 0.16783577, 0.29869229, 0.28394305,
       0.32721258, 0.46014033, 0.54436836, 0.21740087, 0.79986833,
       0.72668445, 0.84929271, 0.2675218 , 0.61482471, 0.65275607,
       0.38681643, 0.41035418, 0.81015755, 0.60036927, 0.89834034,
       0.49003223, 0.82831813, 0.85888947, 0.78844514, 0.88765544,
       0.69886079])

##### Generate Random numbers from thrown dice
np.random.randint(start,stop+1,size)

In [ ]:
dice = np.random.randint(1,7,100)
dice

array([6, 4, 6, 1, 4, 5, 4, 5, 5, 6, 5, 2, 1, 5, 3, 1, 6, 3, 5, 2, 2, 1,
       3, 5, 5, 1, 5, 2, 5, 2, 1, 3, 4, 2, 3, 5, 5, 3, 3, 1, 2, 3, 3, 1,
       6, 2, 3, 5, 1, 6, 6, 2, 3, 2, 6, 5, 3, 1, 6, 1, 2, 6, 1, 2, 4, 2,
       2, 6, 5, 5, 4, 6, 1, 4, 1, 4, 2, 3, 6, 6, 5, 6, 1, 6, 1, 6, 4, 2,
       2, 6, 1, 6, 1, 5, 3, 6, 4, 5, 3, 1])

In [ ]:
np.random.seed(1)
dice = np.random.randint(1,7,100)
dice

array([6, 4, 5, 1, 2, 4, 6, 1, 1, 2, 5, 6, 5, 2, 3, 5, 6, 3, 5, 4, 5, 3,
       5, 6, 3, 5, 2, 2, 1, 6, 2, 2, 6, 2, 2, 1, 5, 2, 1, 1, 6, 4, 3, 2,
       1, 4, 6, 2, 2, 4, 5, 1, 2, 4, 5, 3, 5, 1, 6, 4, 2, 3, 1, 5, 2, 3,
       3, 2, 1, 2, 4, 6, 5, 4, 6, 2, 4, 1, 1, 3, 3, 2, 4, 5, 3, 1, 1, 2,
       2, 6, 4, 1, 1, 6, 6, 5, 6, 3, 5, 4])

##### Generating Normal Distribution
np.random.normal(mean,std_dev,size)

In [ ]:
np.random.seed(64)
Height = np.random.normal(5.5,0.3,size=1000)
Height

array([5.83009688, 4.90521178, 5.15492515, 6.15787491, 4.92956949,
       5.36983099, 5.15932544, 5.19001148, 4.78841241, 5.71100143,
       5.61545264, 6.02514574, 5.14147922, 5.5885383 , 5.51449627,
       5.44861034, 5.34849189, 5.08944579, 5.46922639, 5.3840268 ,
       5.36316827, 5.09224849, 5.3809369 , 5.67838957, 5.08661989,
       5.65353851, 5.33760028, 5.35271777, 5.59784627, 5.72160208,
       5.46098914, 5.48994972, 5.09503311, 5.19214293, 4.93708139,
       5.0924978 , 6.05718509, 6.01149819, 5.08884393, 5.70256471,
       5.38761817, 5.33730617, 5.79101601, 5.7300802 , 5.22225654,
       5.52597094, 5.53915969, 5.90731165, 5.18092949, 5.87020143,
       5.39507143, 5.43266943, 5.61470264, 6.22137293, 5.86225699,
       5.46351051, 5.85441225, 5.43803443, 5.2787915 , 4.9428004 ,
       5.74414537, 5.11560387, 5.99059733, 5.79299414, 5.53823907,
       5.58041495, 5.29481216, 5.41016787, 4.92358914, 5.41755376,
       4.92382537, 5.69434972, 5.47603183, 5.25510962, 5.48110

In [ ]:
from warnings import filterwarnings
filterwarnings ('ignore')

In [ ]:
import seaborn as sns
sns.histplot(data=Height,kde=True)

NameError: name 'Height' is not defined

In [52]:
np.mean(Height)

NameError: name 'Height' is not defined

#### Common functions in Numpy Library

In [53]:
X = np.array([6,4,5,6,4,0,2])
X 

array([6, 4, 5, 6, 4, 0, 2])

In [54]:
type(X)

numpy.ndarray

In [55]:
np.sqrt(X)

array([2.44948974, 2.        , 2.23606798, 2.44948974, 2.        ,
       0.        , 1.41421356])

In [56]:
np.sin(X)

array([-0.2794155 , -0.7568025 , -0.95892427, -0.2794155 , -0.7568025 ,
        0.        ,  0.90929743])

In [59]:
from math import pi
deg = 45
rad = deg*(pi/180)
rad

0.7853981633974483

In [57]:
np.cos(X)

array([ 0.96017029, -0.65364362,  0.28366219,  0.96017029, -0.65364362,
        1.        , -0.41614684])

In [60]:
np.cos(rad)

0.7071067811865476

In [61]:
np.tan(rad)

0.9999999999999999

In [62]:
np.tan(X)

array([-0.29100619,  1.15782128, -3.38051501, -0.29100619,  1.15782128,
        0.        , -2.18503986])

In [63]:
np.log10(X)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9836\3560718848.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(X)


array([0.77815125, 0.60205999, 0.69897   , 0.77815125, 0.60205999,
             -inf, 0.30103   ])

In [64]:
np.exp(X)

array([403.42879349,  54.59815003, 148.4131591 , 403.42879349,
        54.59815003,   1.        ,   7.3890561 ])

#### Plot the curve X*sin(x) - X^2

In [65]:
x = np.arange(-4*pi , 4*pi , 0.1)
x

array([-12.56637061, -12.46637061, -12.36637061, -12.26637061,
       -12.16637061, -12.06637061, -11.96637061, -11.86637061,
       -11.76637061, -11.66637061, -11.56637061, -11.46637061,
       -11.36637061, -11.26637061, -11.16637061, -11.06637061,
       -10.96637061, -10.86637061, -10.76637061, -10.66637061,
       -10.56637061, -10.46637061, -10.36637061, -10.26637061,
       -10.16637061, -10.06637061,  -9.96637061,  -9.86637061,
        -9.76637061,  -9.66637061,  -9.56637061,  -9.46637061,
        -9.36637061,  -9.26637061,  -9.16637061,  -9.06637061,
        -8.96637061,  -8.86637061,  -8.76637061,  -8.66637061,
        -8.56637061,  -8.46637061,  -8.36637061,  -8.26637061,
        -8.16637061,  -8.06637061,  -7.96637061,  -7.86637061,
        -7.76637061,  -7.66637061,  -7.56637061,  -7.46637061,
        -7.36637061,  -7.26637061,  -7.16637061,  -7.06637061,
        -6.96637061,  -6.86637061,  -6.76637061,  -6.66637061,
        -6.56637061,  -6.46637061,  -6.36637061,  -6.26

In [66]:
y = x*np.sin(x)+x**2
y

array([1.57913670e+02, 1.54165836e+02, 1.50470304e+02, 1.46838888e+02,
       1.43282766e+02, 1.39812374e+02, 1.36437305e+02, 1.33166226e+02,
       1.30006800e+02, 1.26965621e+02, 1.24048164e+02, 1.21258741e+02,
       1.18600479e+02, 1.16075303e+02, 1.13683936e+02, 1.11425909e+02,
       1.09299590e+02, 1.07302213e+02, 1.05429932e+02, 1.03677875e+02,
       1.02040214e+02, 1.00510245e+02, 9.90804664e+01, 9.77426795e+01,
       9.64880824e+01, 9.53073749e+01, 9.41908655e+01, 9.31285808e+01,
       9.21103766e+01, 9.11260482e+01, 9.01654404e+01, 8.92185546e+01,
       8.82756523e+01, 8.73273544e+01, 8.63647347e+01, 8.53794069e+01,
       8.43636043e+01, 8.33102515e+01, 8.22130268e+01, 8.10664161e+01,
       7.98657562e+01, 7.86072687e+01, 7.72880832e+01, 7.59062503e+01,
       7.44607442e+01, 7.29514551e+01, 7.13791716e+01, 6.97455536e+01,
       6.80530961e+01, 6.63050842e+01, 6.45055407e+01, 6.26591657e+01,
       6.07712704e+01, 5.88477056e+01, 5.68947845e+01, 5.49192031e+01,
      

In [68]:
import matplotlib as plt
plt.figure(figsize=(16,8))
plt.plot(x,y)
plt.title('plot for y = x*sin(x)+x^2')
plt.grid()
plt.show()

AttributeError: module 'matplotlib' has no attribute 'figure'